### ISSUE TITLE
Gulp watch task fails

### ISSUE THREAD

**Issue by KraigWalker** [thoughtbot/proteus-gulp#14]
When starting a new site, just with all the defaults, the default gulp task returns an error when attempting the watch task.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:1011:11)
  at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by KraigWalker** [comment]
CORRECTION

It appears it's actually the 'views' task that's failing. I tried each one individually.

**Comment by KraigWalker** [comment]
Figured it out. The haml gem wasn't installed on my machine. Potentially get proteus to insure it's installed?

**Comment by joshuaogle** [comment]
There is a haml package that should get installed with `npm install` (or `proteus setup`). I'll look into it to see if there's a bug with it

**Comment by joshuaogle** [comment]
It seems to work fine for me. You may want to try running `npm install` again to see if that's it. If you are still having trouble, I can change which package we're using for that.

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
