### ISSUE TITLE
Gulp deploy fails

### ISSUE THREAD

**Issue by nickbytes** [thoughtbot/proteus-gulp#15]
I'm getting this error message when I use `gulp deploy` command:

```
[13:22:38] Using gulpfile ~/community/Gulpfile.js
[13:22:38] Starting 'deploy'...
/Users/nick/community/node_modules/gulp-gh-pages/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
Error: Error: Command failed: /bin/sh -c git rev-list --pretty=raw --max-count=1 
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
```

I'm not familiar with what might be causing this, any idea?

**Comment by joshuaogle** [comment]
Hey @nickbytes, sorry I didn't get to this in time. This repo was meant as a super simple example of a javascript setup, but it's not nearly fully featured enough for what we would use it for. I'm working on building a Wintersmith kit (http://wintersmith.io/) which I think will work better for everyone wanting a JS setup with more flexbility.

Hope you found something that worked.

**Comment by nickbytes** [comment]
No worries @joshuaogle! I messed with my npm/gulp setup and got it all working.

Wintersmith looks really awesome, had never seen that before. Came across http://www.metalsmith.io/ yesterday, which feels similar, interested in trying out both in future, and see what you come up with! Cheers.
