### ISSUE TITLE
When I $ gulp after $ npm install I get a few errors...

### ISSUE THREAD

**Issue by ClintHubbardJr** [thoughtbot/proteus-gulp#16]
After I go through the Getting Started steps and run $ npm install I get the following error when I try to $ gulp 

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn haml ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
  at child_process.js:1137:20
  at process._tickCallback (node.js:355:11)

I've gone through and made sure that I have everything updated and have any required gems installed. I've also Googled this error and haven't had any luck with the found solutions.

**Comment by joshuaogle** [comment]
It looks like it's a problem with the haml package, and may be the same problem as #14. If you're having the problem too, then switching to another package might be the best solution.

**Comment by ClintHubbardJr** [comment]
Okay. I'll look into a switch.
Thanks.

**Comment by joshuaogle** [comment]
The alternative packages all seem to use the haml.js port, which compiles some things differently and a lot of the way we're used to writing Haml just doesn't work. I'd like to stick with the existing package if we can.

I've tried it out fresh on a couple of other machines and I can't get it to give me the error.
If you run `gem install haml` first, does that solve the problem for you?
Sorry it's giving you trouble, I wish the error message was more informative.

**Comment by ClintHubbardJr** [comment]
Looks like I has some issues with my version of Ruby and RVM... 

This thread helped with my Ruby version 
http://stackoverflow.com/questions/15129355/ruby-2-0-rails-gem-install-error-cannot-load-such-file-openssl

This helped with RVM...  Basically needed to "rvm get head"
https://github.com/rubygems/rubygems/issues/1107

Once the updating was gtg I was able to successfully "gem install haml"

**Comment by johnpuddephatt** [comment]
Having run `npm install` (twice) I was getting the following error when running `gulp`

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
  at errnoException (net.js:904:11)
  at Object.afterWrite (net.js:720:19)
```

But this went away when I explicitly ran  `gem install haml` as mentioned, now everything's fine...
