### ISSUE TITLE
Coffeescript sourcemaps

### ISSUE THREAD

**Issue by zyk** [thoughtbot/proteus-gulp#17]
Hey!

When I try to use sourcemaps the mappings are incorrect.
I've got a application.coffee where in the top I include other coffescript files.

The built javascript output (application.js) have a sourcemap and chrome sees it. But it maps to to the wrong line numbers because of the concat made by gulp-include.

For example, in application.coffe line 34 I've got console.log('start') which runs when loading the site. In chrome's console it maps the console.log output to application.coffee:449 instead of line 34.

Got any clue how to fix it? It seems gulp-include and gulp-sourcemaps are not working together..
Maybe I should create a issue on one of their issue trackers?

Thanks!

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
