### ISSUE TITLE
Haml partials?

### ISSUE THREAD

**Issue by ljuboja** [thoughtbot/proteus-gulp#18]
Hi, 

is it possible to get haml partials to work with proteus-gulp?
Thx

**Comment by dpfranklin** [comment]
Yes - a little late.  See [the haml branch of my fork](https://github.com/dpfranklin/proteus-gulp/tree/haml) for more detail but essentially you just need to do the following.

Swap out gulp-ruby-haml for gulp-haml-coffee.

````
npm uninstall gulp-ruby-haml --save

npm install gulp-haml-coffee --save-dev
````

 Supplement paths to exclude partials from being compiled.

````
haml: ['./source/views/*.haml', '!./source/views/_*.haml'],
````

Add include directive and path to partial in your haml template.

````
+include './source/views/_partial.haml'
````

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
