### ISSUE TITLE
box-sizing warning

### ISSUE THREAD

**Issue by ljuboja** [thoughtbot/proteus-gulp#19]
When I do gulp command I got following:

gulp-ruby-sass: stderr: WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
         on line 410 of /home/ljubisa/sites/shelving/node_modules/node-neat/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss, in `box-sizing'
         from line 3 of /home/ljubisa/sites/shelving/node_modules/node-neat/assets/stylesheets/grid/_grid.scss
         from line 11 of /home/ljubisa/sites/shelving/node_modules/node-neat/assets/stylesheets/_neat.scss

**Comment by joshuaogle** [comment]
This warning will go away when we update this repo after Bourbon 5 comes out (very soon!). It's just a warning though, so everything will still work fine.
